### ISSUE TITLE
Can't Connect Via HTTP

### ISSUE THREAD

**Issue by ghost** [MatteoGgl/docker-gophish#6]
# I must connect to the admin server via HTTPS in order to get a valid response
After creating the **docker-gophish** container via Kitematic and running:
```
docker run -ti --name gophish -p 3333:3333 -p 8083:80 matteoggl/gophish
```
If I try to connect to it like this:
```
http://my-machines'-ip:3333
```
I wont get back a valid response thus:
![invr](https://user-images.githubusercontent.com/27923974/35472446-91656376-036f-11e8-9637-33c798e019ee.PNG)
However, if I run:
```
https://my-machines'-ip:3333
```
I finally get a valid response:
![valr](https://user-images.githubusercontent.com/27923974/35472457-c5e24592-036f-11e8-8f20-e280ff416a61.PNG)

## In order to help avoid headaches I suggest that you change:
```
In your browser, go to http://your-docker-machine-ip:3333
```
to
```
In your browser, go to https://your-docker-machine-ip:3333
```
### Have a nice day!

**Comment by MatteoGgl** [comment]
Solved!
